// <auto-generated />
using System;
using AgileQuotation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgileQuotation.Persistence.Migrations
{
    [DbContext(typeof(AgileQuotationContext))]
    partial class AgileQuotationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("AgileQuotation.Domain.ProductSupplier", b =>
                {
                    b.Property<int>("QuotationProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuotationSupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuotationProductId", "QuotationSupplierId");

                    b.HasIndex("QuotationSupplierId");

                    b.ToTable("ProductSuppliers");
                });

            modelBuilder.Entity("AgileQuotation.Domain.QuotationProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BoardingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CountBySKU")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMonthValidate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastPurchase")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSupplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastValidate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SKU")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusProduct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubBrand")
                        .HasColumnType("TEXT");

                    b.Property<string>("TheGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("TheSubGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeIndAtac")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeSKUPositive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeSituation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeUnit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitBox")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weigth")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuotationProducts");
                });

            modelBuilder.Entity("AgileQuotation.Domain.QuotationSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QuotationSuppliers");
                });

            modelBuilder.Entity("QuotationProductQuotationSupplier", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuppliersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductsId", "SuppliersId");

                    b.HasIndex("SuppliersId");

                    b.ToTable("QuotationProductQuotationSupplier");
                });

            modelBuilder.Entity("AgileQuotation.Domain.ProductSupplier", b =>
                {
                    b.HasOne("AgileQuotation.Domain.QuotationProduct", "QuotationProduct")
                        .WithMany()
                        .HasForeignKey("QuotationProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgileQuotation.Domain.QuotationSupplier", "QuotationSupplier")
                        .WithMany()
                        .HasForeignKey("QuotationSupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotationProduct");

                    b.Navigation("QuotationSupplier");
                });

            modelBuilder.Entity("QuotationProductQuotationSupplier", b =>
                {
                    b.HasOne("AgileQuotation.Domain.QuotationProduct", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgileQuotation.Domain.QuotationSupplier", null)
                        .WithMany()
                        .HasForeignKey("SuppliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
